<?php

use App\Features\AppBoundaries;
use App\Features\AppDrift;
use App\Features\AppFaults;
use App\Http\Controllers\ClearedProblemController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeploymentController;
use App\Http\Controllers\DesignEditsController;
use App\Http\Controllers\DeveloperReviewController;
use App\Http\Controllers\DeveloperReviewGuidanceController;
use App\Http\Controllers\ExperimentController;
use App\Http\Controllers\ExperimentMergeController;
use App\Http\Controllers\FeatureRequestAcceptanceController;
use App\Http\Controllers\FeatureRequestAcceptedFindingController;
use App\Http\Controllers\FeatureRequestAnswerController;
use App\Http\Controllers\FeatureRequestController;
use App\Http\Controllers\FeatureRequestDismissalController;
use App\Http\Controllers\FeatureRequestFindingProposalController;
use App\Http\Controllers\FeatureRequestFollowUpController;
use App\Http\Controllers\FeatureRequestImageController;
use App\Http\Controllers\FeatureRequestKeepTryingController;
use App\Http\Controllers\FeatureRequestPreviewController;
use App\Http\Controllers\FeatureRequestRetryController;
use App\Http\Controllers\FeatureRequestReversionController;
use App\Http\Controllers\FeatureRequestStepChangeController;
use App\Http\Controllers\FeatureRequestVerificationController;
use App\Http\Controllers\FeatureRequestWorkerController;
use App\Http\Controllers\LiveErrorFixController;
use App\Http\Controllers\NewPartController;
use App\Http\Controllers\NewProjectController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\NotificationReadController;
use App\Http\Controllers\Operations\AttentionController;
use App\Http\Controllers\Operations\ChangeController as OperationsChangeController;
use App\Http\Controllers\Operations\DeveloperReviewController as OperationsDeveloperReviewController;
use App\Http\Controllers\PageConsistencyController;
use App\Http\Controllers\PreviewController;
use App\Http\Controllers\PreviewDataController;
use App\Http\Controllers\PreviewEmailController;
use App\Http\Controllers\PreviewFileController;
use App\Http\Controllers\PreviewPersonController;
use App\Http\Controllers\PreviewProblemFixController;
use App\Http\Controllers\PreviewRowController;
use App\Http\Controllers\PreviewScheduledTaskRunController;
use App\Http\Controllers\PreviewSignInController;
use App\Http\Controllers\ProjectCarefulAreaController;
use App\Http\Controllers\ProjectCompatibilityController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProjectDownloadController;
use App\Http\Controllers\ProjectEditorController;
use App\Http\Controllers\ProjectExperimentController;
use App\Http\Controllers\ProjectNameController;
use App\Http\Controllers\ProjectNotesDraftController;
use App\Http\Controllers\ProjectOwnToolController;
use App\Http\Controllers\ProjectPreviewController;
use App\Http\Controllers\ProjectPublishingController;
use App\Http\Controllers\ProjectServiceController;
use App\Http\Controllers\ProjectShareController;
use App\Http\Controllers\ProjectUnderstandingController;
use App\Http\Controllers\RunCancellationController;
use App\Http\Controllers\SharedAppController;
use App\Http\Controllers\ThemeColorController;
use App\Http\Controllers\VerificationShotController;
use App\Http\Controllers\VisualEditController;
use App\Http\Controllers\VisualEditReversionController;
use App\Http\Controllers\VisualLinkController;
use App\Http\Controllers\VisualMotionController;
use App\Http\Controllers\VisualMoveController;
use App\Http\Controllers\VisualPartController;
use App\Http\Controllers\VisualPictureController;
use App\Http\Controllers\VisualTextController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'Welcome')->name('home');

// A link the owner shared: anyone holding it can try the app, with no account.
Route::get('s/{token}', [SharedAppController::class, 'show'])->where('token', '[A-Za-z0-9]{40}')->middleware('throttle:30,1')->name('shared-apps.show');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');

    Route::get('projects', [ProjectController::class, 'index'])->name('projects.index');
    Route::post('projects', [ProjectController::class, 'store'])->name('projects.store');
    Route::post('projects/new', [NewProjectController::class, 'store'])->name('projects.new.store');
    Route::get('projects/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::get('projects/{project}/download', ProjectDownloadController::class)->name('projects.download');
    Route::get('projects/{project}/understanding', [ProjectUnderstandingController::class, 'show'])->name('projects.understanding.show');
    Route::put('projects/{project}/understanding', [ProjectUnderstandingController::class, 'update'])->name('projects.understanding.update');
    Route::get('projects/{project}/developers', [DeveloperReviewController::class, 'index'])->name('projects.developers.index');
    Route::post('projects/{project}/developers', [DeveloperReviewController::class, 'store'])->name('projects.developers.store');
    Route::delete('developer-reviews/{developerReview}', [DeveloperReviewController::class, 'destroy'])->name('developer-reviews.destroy');
    Route::post('developer-reviews/{developerReview}/guidance', [DeveloperReviewGuidanceController::class, 'store'])->name('developer-reviews.guidance.store');
    Route::post('projects/{project}/notes-draft', [ProjectNotesDraftController::class, 'store'])->name('projects.notes-draft.store');
    Route::delete('projects/{project}/notes-draft', [ProjectNotesDraftController::class, 'destroy'])->name('projects.notes-draft.destroy');
    Route::patch('projects/{project}/name', [ProjectNameController::class, 'update'])->name('projects.name.update');
    Route::put('projects/{project}/compatibility', [ProjectCompatibilityController::class, 'update'])->name('projects.compatibility.update');
    Route::put('projects/{project}/careful-areas', [ProjectCarefulAreaController::class, 'update'])->name('projects.careful-areas.update');
    Route::put('feature-requests/{featureRequest}/finding-proposals/{kind}', [FeatureRequestFindingProposalController::class, 'update'])->where('kind', '[a-z_]+')->name('feature-requests.finding-proposals.update');
    Route::post('projects/{project}/services/{service}', [ProjectServiceController::class, 'store'])->whereIn('service', array_keys(config('builder.services', [])))->name('projects.services.store');
    Route::post('projects/{project}/share', [ProjectShareController::class, 'store'])->name('projects.share.store');
    Route::delete('projects/{project}/share', [ProjectShareController::class, 'destroy'])->name('projects.share.destroy');
    Route::put('projects/{project}/publishing', [ProjectPublishingController::class, 'update'])->name('projects.publishing.update');
    Route::post('projects/{project}/deployments', [DeploymentController::class, 'store'])->name('deployments.store');
    Route::post('projects/{project}/live-error-fixes', [LiveErrorFixController::class, 'store'])->name('live-error-fixes.store');
    Route::post('projects/{project}/preview-problem-fixes', [PreviewProblemFixController::class, 'store'])->name('preview-problem-fixes.store');
    Route::post('projects/{project}/preview-sign-ins', [PreviewSignInController::class, 'store'])->name('preview-sign-ins.store');
    Route::post('projects/{project}/preview-people', [PreviewPersonController::class, 'store'])->name('preview-people.store');
    Route::post('projects/{project}/own-tool', [ProjectOwnToolController::class, 'store'])->name('projects.own-tool.store');
    Route::delete('projects/{project}/own-tool', [ProjectOwnToolController::class, 'destroy'])->name('projects.own-tool.destroy');
    Route::delete('projects/{project}/preview-emails', [PreviewEmailController::class, 'destroy'])->name('preview-emails.destroy');
    Route::post('projects/{project}/cleared-problems', [ClearedProblemController::class, 'store'])->name('cleared-problems.store');
    Route::delete('projects/{project}/cleared-problems/{problem}', [ClearedProblemController::class, 'destroy'])->name('cleared-problems.destroy');
    Route::patch('projects/{project}/preview-rows', [PreviewRowController::class, 'update'])->name('preview-rows.update');
    Route::delete('projects/{project}/preview-rows', [PreviewRowController::class, 'destroy'])->name('preview-rows.destroy');
    Route::put('projects/{project}/preview-data', [PreviewDataController::class, 'update'])->name('preview-data.update');
    Route::post('projects/{project}/preview-schedule-runs', [PreviewScheduledTaskRunController::class, 'store'])->name('preview-schedule-runs.store');
    Route::get('projects/{project}/preview-files', [PreviewFileController::class, 'show'])->name('preview-files.show');
    Route::get('projects/{project}/editor', [ProjectEditorController::class, 'show'])->name('projects.editor.show');
    Route::post('projects/{project}/previews', [ProjectPreviewController::class, 'store'])->name('projects.previews.store');
    Route::post('projects/{project}/experiments', [ExperimentController::class, 'store'])->name('experiments.store');
    Route::put('projects/{project}/experiment', [ProjectExperimentController::class, 'update'])->name('projects.experiment.update');
    Route::post('experiments/{experiment}/merge', [ExperimentMergeController::class, 'store'])->name('experiments.merge.store');
    Route::delete('experiments/{experiment}', [ExperimentController::class, 'destroy'])->name('experiments.destroy');
    Route::post('projects/{project}/visual-edits', [VisualEditController::class, 'store'])->name('visual-edits.store');
    Route::post('projects/{project}/visual-moves', [VisualMoveController::class, 'store'])->name('visual-moves.store');
    Route::post('projects/{project}/visual-texts', [VisualTextController::class, 'store'])->name('visual-texts.store');
    Route::post('projects/{project}/visual-links', [VisualLinkController::class, 'store'])->name('visual-links.store');
    Route::post('projects/{project}/visual-motions', [VisualMotionController::class, 'store'])->name('visual-motions.store');
    Route::post('projects/{project}/theme-colors', [ThemeColorController::class, 'store'])->name('theme-colors.store');
    Route::post('projects/{project}/design-edits', [DesignEditsController::class, 'store'])->name('design-edits.store');
    Route::delete('projects/{project}/design-edits', [DesignEditsController::class, 'destroy'])->name('design-edits.destroy');
    Route::post('projects/{project}/visual-pictures', [VisualPictureController::class, 'store'])->name('visual-pictures.store');
    Route::post('projects/{project}/visual-parts', [VisualPartController::class, 'store'])->name('visual-parts.store');
    Route::delete('projects/{project}/visual-parts', [VisualPartController::class, 'destroy'])->name('visual-parts.destroy');
    Route::post('projects/{project}/new-parts', [NewPartController::class, 'store'])->name('new-parts.store');
    Route::post('projects/{project}/page-consistency', [PageConsistencyController::class, 'store'])->name('page-consistency.store');
    Route::post('visual-edits/{visualEdit}/reversion', [VisualEditReversionController::class, 'store'])->name('visual-edits.reversion.store');
    Route::delete('visual-edits/{visualEdit}/reversion', [VisualEditReversionController::class, 'destroy'])->name('visual-edits.reversion.destroy');

    Route::post('projects/{project}/feature-requests', [FeatureRequestController::class, 'store'])->name('feature-requests.store');
    Route::get('feature-requests/{featureRequest}', [FeatureRequestController::class, 'show'])->name('feature-requests.show');
    Route::get('feature-requests/{featureRequest}/images/{image}', [FeatureRequestImageController::class, 'show'])->whereNumber('image')->name('feature-requests.images.show');
    Route::get('verifications/{verification}/shots/{shot}', [VerificationShotController::class, 'show'])->whereNumber('shot')->name('verifications.shots.show');
    Route::post('feature-requests/{featureRequest}/follow-ups', [FeatureRequestFollowUpController::class, 'store'])->name('feature-requests.follow-ups.store');
    Route::post('feature-requests/{featureRequest}/step-changes', [FeatureRequestStepChangeController::class, 'store'])->name('feature-requests.step-changes.store');
    Route::post('feature-requests/{featureRequest}/verifications', [FeatureRequestVerificationController::class, 'store'])->name('feature-requests.verifications.store');
    Route::post('feature-requests/{featureRequest}/acceptance', [FeatureRequestAcceptanceController::class, 'store'])->name('feature-requests.acceptance.store');
    Route::post('feature-requests/{featureRequest}/answers', [FeatureRequestAnswerController::class, 'store'])->name('feature-requests.answers.store');
    Route::post('feature-requests/{featureRequest}/retries', [FeatureRequestRetryController::class, 'store'])->name('feature-requests.retries.store');
    Route::post('feature-requests/{featureRequest}/keep-trying', [FeatureRequestKeepTryingController::class, 'store'])->name('feature-requests.keep-trying.store');
    Route::post('feature-requests/{featureRequest}/worker', [FeatureRequestWorkerController::class, 'store'])->name('feature-requests.worker.store');
    Route::post('feature-requests/{featureRequest}/reversion', [FeatureRequestReversionController::class, 'store'])->name('feature-requests.reversion.store');
    Route::post('feature-requests/{featureRequest}/dismissal', [FeatureRequestDismissalController::class, 'store'])->name('feature-requests.dismissal.store');
    Route::delete('feature-requests/{featureRequest}/dismissal', [FeatureRequestDismissalController::class, 'destroy'])->name('feature-requests.dismissal.destroy');
    Route::post('feature-requests/{featureRequest}/accepted-findings/{kind}', [FeatureRequestAcceptedFindingController::class, 'store'])->whereIn('kind', [...AppBoundaries::OWNED, ...AppFaults::OWNED, AppDrift::GREW])->name('feature-requests.accepted-findings.store');
    Route::delete('feature-requests/{featureRequest}/accepted-findings/{kind}', [FeatureRequestAcceptedFindingController::class, 'destroy'])->whereIn('kind', [...AppBoundaries::OWNED, ...AppFaults::OWNED, AppDrift::GREW])->name('feature-requests.accepted-findings.destroy');
    Route::post('feature-requests/{featureRequest}/previews', [FeatureRequestPreviewController::class, 'store'])->name('feature-requests.previews.store');
    Route::get('previews/{preview}', [PreviewController::class, 'show'])->name('previews.show');
    Route::delete('previews/{preview}', [PreviewController::class, 'destroy'])->name('previews.destroy');
    Route::get('notifications/{notification}', [NotificationController::class, 'show'])->name('notifications.show');
    Route::post('notifications/read', NotificationReadController::class)->name('notifications.read');
    Route::post('runs/{run}/cancellation', [RunCancellationController::class, 'store'])->name('runs.cancellation.store');
});

// For operators only: every owner's changes, and what needs attention.
Route::middleware(['auth', 'verified', 'can:viewOperations'])->prefix('operations')->name('operations.')->group(function () {
    Route::get('/', AttentionController::class)->name('attention');
    Route::get('changes', [OperationsChangeController::class, 'index'])->name('changes.index');
    Route::get('changes/{featureRequest}', [OperationsChangeController::class, 'show'])->name('changes.show');
    // Our own developers answer the owners who asked for one.
    Route::get('developer-reviews', [OperationsDeveloperReviewController::class, 'index'])->name('developer-reviews.index');
    Route::get('developer-reviews/{developerReview}', [OperationsDeveloperReviewController::class, 'show'])->name('developer-reviews.show');
    Route::put('developer-reviews/{developerReview}', [OperationsDeveloperReviewController::class, 'update'])->name('developer-reviews.update');
    Route::get('developer-reviews/{developerReview}/request.md', [OperationsDeveloperReviewController::class, 'request'])->name('developer-reviews.request');
    Route::get('developer-reviews/{developerReview}/code', [OperationsDeveloperReviewController::class, 'code'])->name('developer-reviews.code');
    Route::get('developer-reviews/{developerReview}/change.patch', [OperationsDeveloperReviewController::class, 'change'])->name('developer-reviews.change');
});

require __DIR__.'/settings.php';
